name: Generate Icons JSON

on:
  push:
    paths:
      - "app/**" # 监控 app 文件夹的改动
  workflow_dispatch: # 手动触发

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Scan images and generate JSON
      run: node .github/scripts/generate-icons.js

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add app.json
        git commit -m "Update app.json with scanned icons"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
